//
// Created by maltenzo on 1/1/21->
//
//#include "cpu.H"
#include "instructions.h"
#include "cpu_reg.c"

typedef struct Memory{
    uint8_t memory [0xFFFF];
}Memory_t;

typedef struct CPU{
    struct registros reg;
    Memory_t *mem;
    uint16_t pc;
    uint16_t sp;
    bool is_halted;
}CPU_t;

extern CPU_t* cpu_;
extern CPU_t* new_cpu();
extern void del_cpu();
extern void write_mem(uint16_t offset, uint8_t dato);
extern uint8_t read_mem(uint16_t pc);

//int value8Low,value8High,value16 = 0;
//#define  value8Low = read(cpu_.mem, cpu_.pc+1);
//#define  value8High = read(cpu_.mem, cpu_.pc+2);;
//#define  value16 = value8High << 8 | value8Low;

/*
void ParseBitOperation(uint8_t opCode){
    uint8_t value8Low = read(cpu_.mem, cpu_.pc+1);
    uint8_t value8High = read(cpu_.mem, cpu_.pc+2);
    uint16_t value16 = value8High << 8 | value8Low;

    switch (opCode)
    {
        //case 0x00: NOP(); break;
        //case 0x01: LD_R16_N16(get_bc(&cpu_.reg) , value16); break;
        //case 0x02: LD_R16_A(*get_bc(&cpu_.reg)); break;
        //case 0x03: INC_R16(get_bc(&cpu_.reg)); break;
        //case 0x04: INC_R8(&cpu_.reg.B); break;
        //case 0x05: DEC_R8(&cpu_.reg.B); break;
        //case 0x06: LD_R8_N8(&cpu_.reg.B, value8Low); break;
        //case 0x07: RLCA(); break;
        //case 0x08: LD_N16_SP(value16); break;
        //case 0x09: ADD_HL_R16(*get_bc(&cpu_.reg)); break;
        //case 0x0A: LD_A_R16(*get_bc(&cpu_.reg)); break;
        //case 0x0B: DEC_R16(get_bc(&cpu_.reg)); break;
        //case 0x0C: INC_R8(&cpu_.reg.C); break;
        //case 0x0D: DEC_R8(&cpu_.reg.C); break;
        //case 0x0E: LD_R8_N8(&cpu_.reg.C, value8Low); break;
        //case 0x0F: RRC_A(); break;
        //case 0x11: LD_R16_N16(get_de(&cpu_.reg), value16); break;
        //case 0x12: LD_R16_A(*get_de(&cpu_.reg)); break;
        //case 0x13: INC_R16(get_de(&cpu_.reg)); break;
        //case 0x14: INC_R8(&cpu_.reg.D); break;
        //case 0x15: DEC_R8(&cpu_.reg.D); break;
        //case 0x16: LD_R8_N8(&cpu_.reg.D, value8Low); break;
        //case 0x17: RLA(); break;
        //case 0x18: JR_N8(value8Low); break;
        //case 0x19: ADD_HL_R16(*get_de(&cpu_.reg)); break;
        //case 0x1A: LD_A_R16(*get_de(&cpu_.reg)); break;
        //case 0x1B: DEC_R16(get_de(&cpu_.reg)); break;
        //case 0x1C: INC_R8(&cpu_.reg.E); break;
        //case 0x1D: DEC_R8(&cpu_.reg.E); break;
        //case 0x1E: LD_R8_N8(&cpu_.reg.E, value8Low); break;
        //case 0x1F: RR_A(); break;
        //case 0x20: JRNZ_N8(value8Low); break;
        //case 0x21: LD_R16_N16(get_hl(&cpu_.reg), value16); break;
        //case 0x22: LD_HLI_A(); break;
        //case 0x23: INC_R16(get_hl(&cpu_.reg)); break;
        //case 0x24: INC_R8(&cpu_.reg.H); break;
        //case 0x25: DEC_R8(&cpu_.reg.H); break;
        //case 0x26: LD_R8_N8(&cpu_.reg.H, value8Low); break;
        //case 0x27: DAA(); break;
        //case 0x28: JRZ_N8(value8Low); break;
        //case 0x29: ADD_HL_R16(*get_hl(&cpu_.reg)); break;
        //case 0x2A: LD_A_HLI(); break;
        //case 0x2B: DEC_R16(get_hl(&cpu_.reg)); break;
        //case 0x2C: INC_R8(&cpu_.reg.L); break;
        //case 0x2D: DEC_R8(&cpu_.reg.L); break;
        //case 0x2E: LD_R8_N8(&cpu_.reg.L, value8Low); break;
        //case 0x2F: CPL(); break;
        //case 0x30: JRNC_N8(value8Low); break;
        //case 0x31: LD_SP_N16(value16); break;
        //case 0x32: LD_HLD_A(); break;
        //case 0x33: INC_SP(); break;
        //case 0x34: INC_HL(); break;
        //case 0x35: DEC_HL(); break;
        //case 0x36: LD_HL_N8(value8Low); break;
        //case 0x37: SCF(); break;
        //case 0x38: JRC_N8(value8Low); break;
        //case 0x39: ADD_HL_SP(); break;
        //case 0x3A: LD_A_HLD(); break;
        //case 0x3B: DEC_SP(); break;
        //case 0x3C: INC_R8(&cpu_.reg.A); break;
        //case 0x3D: DEC_R8(&cpu_.reg.A); break;
        //case 0x3E: LD_R8_N8(&cpu_.reg.A, value8Low); break;
        //case 0x3F: CCF(); break;
        //case 0x40: LD_R8_R8(&cpu_.reg.B, cpu_.reg.B); break;
        //case 0x41: LD_R8_R8(&cpu_.reg.B, cpu_.reg.C); break;
        //case 0x42: LD_R8_R8(&cpu_.reg.B, cpu_.reg.D); break;
        //case 0x43: LD_R8_R8(&cpu_.reg.B, cpu_.reg.E); break;
        //case 0x44: LD_R8_R8(&cpu_.reg.B, cpu_.reg.H); break;
        //case 0x45: LD_R8_R8(&cpu_.reg.B, cpu_.reg.L); break;
        //case 0x46: LD_R8_HL(&cpu_.reg.B); break;
        //case 0x47: LD_R8_R8(&cpu_.reg.B, cpu_.reg.A); break;
        //case 0x48: LD_R8_R8(&cpu_.reg.C, cpu_.reg.B); break;
        //case 0x49: LD_R8_R8(&cpu_.reg.C, cpu_.reg.C); break;
        //case 0x4A: LD_R8_R8(&cpu_.reg.C, cpu_.reg.D); break;
        //case 0x4B: LD_R8_R8(&cpu_.reg.C, cpu_.reg.E); break;
        //case 0x4C: LD_R8_R8(&cpu_.reg.C, cpu_.reg.H); break;
        //case 0x4D: LD_R8_R8(&cpu_.reg.C, cpu_.reg.L); break;
        //case 0x4E: LD_R8_HL(&cpu_.reg.C); break;
        //case 0x4F: LD_R8_R8(&cpu_.reg.C, cpu_.reg.A); break;
        //case 0x50: LD_R8_R8(&cpu_.reg.D, cpu_.reg.B); break;
        //case 0x51: LD_R8_R8(&cpu_.reg.D, cpu_.reg.C); break;
        //case 0x52: LD_R8_R8(&cpu_.reg.D, cpu_.reg.D); break;
        //case 0x53: LD_R8_R8(&cpu_.reg.D, cpu_.reg.E); break;
        //case 0x54: LD_R8_R8(&cpu_.reg.D, cpu_.reg.H); break;
        //case 0x55: LD_R8_R8(&cpu_.reg.D, cpu_.reg.L); break;
        //case 0x56: LD_R8_HL(&cpu_.reg.D); break;
        //case 0x57: LD_R8_R8(&cpu_.reg.D, cpu_.reg.A); break;
        //case 0x58: LD_R8_R8(&cpu_.reg.E, cpu_.reg.B); break;
        //case 0x59: LD_R8_R8(&cpu_.reg.E, cpu_.reg.C); break;
        //case 0x5A: LD_R8_R8(&cpu_.reg.E, cpu_.reg.D); break;
        //case 0x5B: LD_R8_R8(&cpu_.reg.E, cpu_.reg.E); break;
        //case 0x5C: LD_R8_R8(&cpu_.reg.E, cpu_.reg.H); break;
        //case 0x5D: LD_R8_R8(&cpu_.reg.E, cpu_.reg.L); break;
        //case 0x5E: LD_R8_HL(&cpu_.reg.E); break;
        //case 0x5F: LD_R8_R8(&cpu_.reg.E, cpu_.reg.A); break;
        //case 0x60: LD_R8_R8(&cpu_.reg.H, cpu_.reg.B); break;
        //case 0x61: LD_R8_R8(&cpu_.reg.H, cpu_.reg.C); break;
        //case 0x62: LD_R8_R8(&cpu_.reg.H, cpu_.reg.D); break;
        //case 0x63: LD_R8_R8(&cpu_.reg.H, cpu_.reg.E); break;
        //case 0x64: LD_R8_R8(&cpu_.reg.H, cpu_.reg.H); break;
        //case 0x65: LD_R8_R8(&cpu_.reg.H, cpu_.reg.L); break;
        //case 0x66: LD_R8_HL(&cpu_.reg.H); break;
        //case 0x67: LD_R8_R8(&cpu_.reg.H, cpu_.reg.A); break;
        //case 0x68: LD_R8_R8(&cpu_.reg.L, cpu_.reg.B); break;
        //case 0x69: LD_R8_R8(&cpu_.reg.L, cpu_.reg.C); break;
        //case 0x6A: LD_R8_R8(&cpu_.reg.L, cpu_.reg.D); break;
        //case 0x6B: LD_R8_R8(&cpu_.reg.L, cpu_.reg.E); break;
        //case 0x6C: LD_R8_R8(&cpu_.reg.L, cpu_.reg.H); break;
        //case 0x6D: LD_R8_R8(&cpu_.reg.L, cpu_.reg.L); break;
        //case 0x6E: LD_R8_HL(&cpu_.reg.L); break;
        //case 0x6F: LD_R8_R8(&cpu_.reg.L, cpu_.reg.A); break;
        //case 0x70: LD_HL_R8(cpu_.reg.B); break;
        //case 0x71: LD_HL_R8(cpu_.reg.C); break;
        //case 0x72: LD_HL_R8(cpu_.reg.D); break;
        //case 0x73: LD_HL_R8(cpu_.reg.E); break;
        //case 0x74: LD_HL_R8(cpu_.reg.H); break;
        //case 0x75: LD_HL_R8(cpu_.reg.L); break;
        //case 0x76: HALT(); break;
        //case 0x77: LD_HL_R8(cpu_.reg.A); break;
        //case 0x78: LD_R8_R8(&cpu_.reg.A, cpu_.reg.B); break;
        //case 0x79: LD_R8_R8(&cpu_.reg.A, cpu_.reg.C); break;
        //case 0x7A: LD_R8_R8(&cpu_.reg.A, cpu_.reg.D); break;
        //case 0x7B: LD_R8_R8(&cpu_.reg.A, cpu_.reg.E); break;
        //case 0x7C: LD_R8_R8(&cpu_.reg.A, cpu_.reg.H); break;
        //case 0x7D: LD_R8_R8(&cpu_.reg.A, cpu_.reg.L); break;
        //case 0x7E: LD_R8_HL(&cpu_.reg.A); break;
        //case 0x80: ADD_A_R8(cpu_.reg.B); break;
        //case 0x81: ADD_A_R8(cpu_.reg.C); break;
        //case 0x82: ADD_A_R8(cpu_.reg.D); break;
        //case 0x83: ADD_A_R8(cpu_.reg.E); break;
        //case 0x84: ADD_A_R8(cpu_.reg.H); break;
        //case 0x85: ADD_A_R8(cpu_.reg.L); break;
        //case 0x86: ADD_A_HL(); break;
        //case 0x87: ADD_A_R8(cpu_.reg.A); break;
        //case 0x88: ADC_A_R8(cpu_.reg.B); break;
        //case 0x89: ADC_A_R8(cpu_.reg.C); break;
        //case 0x8A: ADC_A_R8(cpu_.reg.D); break;
        //case 0x8B: ADC_A_R8(cpu_.reg.E); break;
        //case 0x8C: ADC_A_R8(cpu_.reg.H); break;
        //case 0x8D: ADC_A_R8(cpu_.reg.L); break;
        //case 0x8E: ADC_A_HL(); break;
        //case 0x8F: ADC_A_R8(cpu_.reg.A); break;
        //case 0x90: SUB_A_R8(cpu_.reg.B); break;
        //case 0x91: SUB_A_R8(cpu_.reg.C); break;
        //case 0x92: SUB_A_R8(cpu_.reg.D); break;
        //case 0x93: SUB_A_R8(cpu_.reg.E); break;
        //case 0x94: SUB_A_R8(cpu_.reg.H); break;
        //case 0x95: SUB_A_R8(cpu_.reg.L); break;
        //case 0x96: SUB_A_HL(); break;
        //case 0x97: SUB_A_R8(cpu_.reg.A); break;
        //case 0x98: SBC_A_R8(cpu_.reg.B); break;
        //case 0x99: SBC_A_R8(cpu_.reg.C); break;
        //case 0x9A: SBC_A_R8(cpu_.reg.D); break;
        //case 0x9B: SBC_A_R8(cpu_.reg.E); break;
        //case 0x9C: SBC_A_R8(cpu_.reg.H); break;
        //case 0x9D: SBC_A_R8(cpu_.reg.L); break;
        //case 0x9E: SBC_A_HL(); break;
        //case 0x9F: SBC_A_R8(cpu_.reg.A); break;
        //case 0xA0: AND_A_R8(cpu_.reg.B); break;
        //case 0xA1: AND_A_R8(cpu_.reg.C); break;
        //case 0xA2: AND_A_R8(cpu_.reg.D); break;
        //case 0xA3: AND_A_R8(cpu_.reg.E); break;
        //case 0xA4: AND_A_R8(cpu_.reg.H); break;
        //case 0xA5: AND_A_R8(cpu_.reg.L); break;
        //case 0xA6: AND_A_HL(); break;
        //case 0xA7: AND_A_R8(cpu_.reg.A); break;
        //case 0xA8: XOR_A_R8(cpu_.reg.B); break;
        //case 0xA9: XOR_A_R8(cpu_.reg.C); break;
        //case 0xAA: XOR_A_R8(cpu_.reg.D); break;
        //case 0xAB: XOR_A_R8(cpu_.reg.E); break;
        //case 0xAC: XOR_A_R8(cpu_.reg.H); break;
        //case 0xAD: XOR_A_R8(cpu_.reg.L); break;
        //case 0xAE: XOR_A_HL(); break;
        //case 0xAF: XOR_A_R8(cpu_.reg.A); break;
        //case 0xB0: OR_A_R8(cpu_.reg.B); break;
        //case 0xB1: OR_A_R8(cpu_.reg.C); break;
        //case 0xB2: OR_A_R8(cpu_.reg.D); break;
        //case 0xB3: OR_A_R8(cpu_.reg.E); break;
        //case 0xB4: OR_A_R8(cpu_.reg.H); break;
        //case 0xB5: OR_A_R8(cpu_.reg.L); break;
        //case 0xB6: OR_A_HL(); break;
        //case 0xB7: OR_A_R8(cpu_.reg.A); break;
        //case 0xB8: CP_A_R8(cpu_.reg.B); break;
        //case 0xB9: CP_A_R8(cpu_.reg.C); break;
        //case 0xBA: CP_A_R8(cpu_.reg.D); break;
        //case 0xBB: CP_A_R8(cpu_.reg.E); break;
        //case 0xBC: CP_A_R8(cpu_.reg.H); break;
        //case 0xBD: CP_A_R8(cpu_.reg.L); break;
        //case 0xBE: CP_A_HL(); break;
        //case 0xBF: CP_A_R8(cpu_.reg.A); break;
        //case 0xC0: RETNZ(); break;
        //case 0xC1: POP_R16(get_bc(&cpu_.reg)); break;
        //case 0xC2: JPNZ_N16(value16); break;
        //case 0xC3: JP_N16(value16);   break;
        //case 0xC4: CALLNZ_N16(value16); break;
        //case 0xC5: PUSH_R16(*get_bc(&cpu_.reg)); break;
        //case 0xC6: ADD_A_N8(value8Low); break;
        //case 0xC7: RST_VEC(0x00); break;
        //case 0xC8: RETZ(); break;
        //case 0xC9: RET(); break;
        //case 0xCA: JPZ_N16(value16);  break;
        //case 0xCB: ParseBitOperation(value8Low); break;
        //case 0xCC: CALLZ_N16(value16); break;
        //case 0xCD: CALL_N16(value16); break;
        //case 0xCE: ADC_A_N8(value8Low); break;
        //case 0xCF: RST_VEC(0x08); break;
        //case 0xD0: RETNC(); break;
        //case 0xD1: POP_R16(get_de(&cpu_.reg)); break;
        //case 0xD2: JPNC_N16(value16); break;
        //case 0xD4: CALLNC_N16(value16); break;
        //case 0xD5: PUSH_R16(*get_de(&cpu_.reg)); break;
        //case 0xD6: SUB_A_N8(value8Low); break;
        //case 0xD7: RST_VEC(0x10); break;
        //case 0xD8: RETC(); break;
        //case 0xD9: RETI(); break;
        //case 0xDA: JPC_N16(value16);  break;
        //case 0xDC: CALLC_N16(value16); break;
        //case 0xDE: SBC_A_N8(value8Low); break;
        //case 0xDF: RST_VEC(0x18); break;
        //case 0xE0: LDH_N16_A(value8Low); break;
        //case 0xE1: POP_R16(get_hl(&cpu_.reg)); break;
        //case 0xE2: LDH_C_A(); break;
        //case 0xE5: PUSH_R16(*get_hl(&cpu_.reg)); break;
        //case 0xE6: AND_A_N8(value8Low); break;
        //case 0xE7: RST_VEC(0x20); break;
        //case 0xE8: ADD_SP_E8(value8Low); break;
        //case 0xE9: JP_HL(); break;
        //case 0xEA: LD_N16_A(value16); break;
        //case 0xEE: XOR_A_N8(value8Low); break;
        //case 0xEF: RST_VEC(0x28); break;
        //case 0xF0: LDH_A_N16(value8Low); break;
        //case 0xF1: POP_AF(); break;
        //case 0xF2: LDH_A_C(); break;
        //case 0xF3: DI(); break;
        //case 0xF5: PUSH_R16(*get_af(&cpu_.reg)); break;
        //case 0xF6: OR_A_N8(value8Low); break;
        //case 0xF7: RST_VEC(0x30); break;
        //case 0xF8: LD_HL_SP_E8(value8Low); break;
        //case 0xF9: LD_SP_HL(); break;
        //case 0xFA: LD_A_N16(value16); break;
        //case 0xFB: EI(); break;
        //case 0xFE: CP_A_N8(value8Low); break;
        //case 0xFF: RST_VEC(0x38); break;
        //case 0x7F: LD_R8_R8(&cpu_.reg.A, cpu_.reg.A); break;
        default: cpu_.pc += 1; break;
    }

};
*/
